### ISSUE TITLE
remove unused import from utils/__init__.py

### ISSUE THREAD

**Issue by deppen8** [reghbali/pyalfe#16]
https://github.com/reghbali/pyalfe/blob/aac439c13d46a82e7c5ab873f5e1c7455619b11d/pyalfe/utils/__init__.py#L1-L2

**Comment by reghbali** [comment]
As we discussed yesterday, looks like ruff removed these which broke the code because I was importing them in main.py. #26 adds the import back and changes ruff configuration to ignore a few rule for __init__.py files.
